### ISSUE TITLE
Error when accessing a roadmap

### ISSUE THREAD

**Issue by nbourdau** [Coren/redmine_advanced_roadmap_v2#23]
When I open the roadmap page of a project, I get a "Page not found error" with redmine 2.5.2 (Debian Jessie). I get the following in the log:

```
Started GET "/projects/dummy_project/roadmap" for 127.0.0.1 at 2015-01-05 23:48:23 +0100
Processing by VersionsController#index as HTML
  Parameters: {"project_id"=>"dummy_project"}
  Current user: admin (id=1)
  Rendered plugins/advanced_roadmap_v2/app/views/versions/_total.html.erb (2.0ms)
  Rendered plugins/advanced_roadmap_v2/app/views/versions/index.html.erb within layouts/base (6.7ms)
Completed 500 Internal Server Error in 24ms

ActiveRecord::RecordNotFound (Couldn't find all Issues with 'id': (all, {:conditions=>{:parent_id=>nil, :tracker_id=>["2"]}, :include=>[:status, :tracker, :priority], :order=>"trackers.position, issues.subject"}) [WHERE `issues`.`fixed_version_id` = ? AND (projects.status <> 9 AND projects.id IN (SELECT em.project_id FROM enabled_modules em WHERE em.name='issue_tracking'))] (found 0 results, but was looking for 2)):
  /usr/lib/ruby/vendor_ruby/active_record/relation/finder_methods.rb:320:in `raise_record_not_found_exception!'
  /usr/lib/ruby/vendor_ruby/active_record/relation/finder_methods.rb:452:in `find_some'
  /usr/lib/ruby/vendor_ruby/active_record/relation/finder_methods.rb:416:in `find_with_ids'
  /usr/lib/ruby/vendor_ruby/active_record/relation/finder_methods.rb:68:in `find'
  plugins/advanced_roadmap_v2/lib/advanced_roadmap/version_patch.rb:105:in `sorted_fixed_issues'
  plugins/advanced_roadmap_v2/app/views/versions/index.html.erb:10:in `block in _plugins_advanced_roadmap_v__app_views_versions_index_html_erb__721153103338422235_38426560'
  plugins/advanced_roadmap_v2/app/views/versions/index.html.erb:8:in `each'
  plugins/advanced_roadmap_v2/app/views/versions/index.html.erb:8:in `_plugins_advanced_roadmap_v__app_views_versions_index_html_erb__721153103338422235_38426560'
  /usr/lib/ruby/vendor_ruby/action_view/template.rb:145:in `block in render'
  /usr/lib/ruby/vendor_ruby/active_support/notifications.rb:161:in `instrument'
  /usr/lib/ruby/vendor_ruby/action_view/template.rb:339:in `instrument'
  /usr/lib/ruby/vendor_ruby/action_view/template.rb:143:in `render'
  /usr/lib/ruby/vendor_ruby/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
  /usr/lib/ruby/vendor_ruby/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  /usr/lib/ruby/vendor_ruby/active_support/notifications.rb:159:in `block in instrument'
  /usr/lib/ruby/vendor_ruby/active_support/notifications/instrumenter.rb:20:in `instrument'
  /usr/lib/ruby/vendor_ruby/active_support/notifications.rb:159:in `instrument'
  /usr/lib/ruby/vendor_ruby/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  /usr/lib/ruby/vendor_ruby/action_view/renderer/template_renderer.rb:54:in `block in render_template'
  /usr/lib/ruby/vendor_ruby/action_view/renderer/template_renderer.rb:62:in `render_with_layout'
  /usr/lib/ruby/vendor_ruby/action_view/renderer/template_renderer.rb:53:in `render_template'
  /usr/lib/ruby/vendor_ruby/action_view/renderer/template_renderer.rb:17:in `render'
  /usr/lib/ruby/vendor_ruby/action_view/renderer/renderer.rb:42:in `render_template'
  /usr/lib/ruby/vendor_ruby/action_view/renderer/renderer.rb:23:in `render'
  /usr/lib/ruby/vendor_ruby/action_view/rendering.rb:99:in `_render_template'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/streaming.rb:217:in `_render_template'
  /usr/lib/ruby/vendor_ruby/action_view/rendering.rb:82:in `render_to_body'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/rendering.rb:32:in `render_to_body'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/renderers.rb:32:in `render_to_body'
  /usr/lib/ruby/vendor_ruby/abstract_controller/rendering.rb:25:in `render'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/rendering.rb:16:in `render'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  /usr/lib/ruby/vendor_ruby/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /usr/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  /usr/lib/ruby/vendor_ruby/active_support/core_ext/benchmark.rb:12:in `ms'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:41:in `block in render'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  /usr/lib/ruby/vendor_ruby/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:40:in `render'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/implicit_render.rb:10:in `default_render'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/implicit_render.rb:5:in `send_action'
  /usr/lib/ruby/vendor_ruby/abstract_controller/base.rb:189:in `process_action'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/rendering.rb:10:in `process_action'
  /usr/lib/ruby/vendor_ruby/abstract_controller/callbacks.rb:20:in `block in process_action'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:113:in `call'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:113:in `call'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:166:in `block in halting'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:149:in `call'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:149:in `call'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:149:in `call'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:166:in `call'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:166:in `block in halting'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:166:in `call'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:166:in `block in halting'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:166:in `call'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:166:in `block in halting'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:166:in `call'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:166:in `block in halting'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:166:in `call'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:166:in `block in halting'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:229:in `call'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:229:in `block in halting'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:166:in `call'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:166:in `block in halting'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:86:in `call'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:86:in `run_callbacks'
  /usr/lib/ruby/vendor_ruby/abstract_controller/callbacks.rb:19:in `process_action'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/rescue.rb:29:in `process_action'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  /usr/lib/ruby/vendor_ruby/active_support/notifications.rb:159:in `block in instrument'
  /usr/lib/ruby/vendor_ruby/active_support/notifications/instrumenter.rb:20:in `instrument'
  /usr/lib/ruby/vendor_ruby/active_support/notifications.rb:159:in `instrument'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/instrumentation.rb:30:in `process_action'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/params_wrapper.rb:250:in `process_action'
  /usr/lib/ruby/vendor_ruby/active_record/railties/controller_runtime.rb:18:in `process_action'
  /usr/lib/ruby/vendor_ruby/abstract_controller/base.rb:136:in `process'
  /usr/lib/ruby/vendor_ruby/action_view/rendering.rb:30:in `process'
  /usr/lib/ruby/vendor_ruby/action_controller/metal.rb:196:in `dispatch'
  /usr/lib/ruby/vendor_ruby/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  /usr/lib/ruby/vendor_ruby/action_controller/metal.rb:232:in `block in action'
  /usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:82:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:82:in `dispatch'
  /usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:50:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/journey/router.rb:73:in `block in call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/journey/router.rb:59:in `each'
  /usr/lib/ruby/vendor_ruby/action_dispatch/journey/router.rb:59:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:678:in `call'
  /usr/lib/ruby/vendor_ruby/rack/openid.rb:98:in `call'
  /usr/lib/ruby/vendor_ruby/rack/etag.rb:23:in `call'
  /usr/lib/ruby/vendor_ruby/rack/conditionalget.rb:25:in `call'
  /usr/lib/ruby/vendor_ruby/rack/head.rb:11:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/params_parser.rb:27:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/flash.rb:254:in `call'
  /usr/lib/ruby/vendor_ruby/rack/session/abstract/id.rb:225:in `context'
  /usr/lib/ruby/vendor_ruby/rack/session/abstract/id.rb:220:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/cookies.rb:560:in `call'
  /usr/lib/ruby/vendor_ruby/active_record/query_cache.rb:36:in `call'
  /usr/lib/ruby/vendor_ruby/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:82:in `run_callbacks'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/callbacks.rb:27:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/remote_ip.rb:76:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:38:in `call_app'
  /usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:20:in `block in call'
  /usr/lib/ruby/vendor_ruby/active_support/tagged_logging.rb:68:in `block in tagged'
  /usr/lib/ruby/vendor_ruby/active_support/tagged_logging.rb:26:in `tagged'
  /usr/lib/ruby/vendor_ruby/active_support/tagged_logging.rb:68:in `tagged'
  /usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:20:in `call'
  /usr/lib/ruby/vendor_ruby/request_store/middleware.rb:8:in `call'
  /usr/lib/ruby/vendor_ruby/active_record/query_cache.rb:36:in `call'
  /usr/lib/ruby/vendor_ruby/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  /usr/lib/ruby/vendor_ruby/active_support/callbacks.rb:82:in `run_callbacks'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/callbacks.rb:27:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/remote_ip.rb:76:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:38:in `call_app'
  /usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:20:in `block in call'
  /usr/lib/ruby/vendor_ruby/active_support/tagged_logging.rb:68:in `block in tagged'
  /usr/lib/ruby/vendor_ruby/active_support/tagged_logging.rb:26:in `tagged'
  /usr/lib/ruby/vendor_ruby/active_support/tagged_logging.rb:68:in `tagged'
  /usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:20:in `call'
  /usr/lib/ruby/vendor_ruby/request_store/middleware.rb:8:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/request_id.rb:21:in `call'
  /usr/lib/ruby/vendor_ruby/rack/methodoverride.rb:21:in `call'
  /usr/lib/ruby/vendor_ruby/rack/runtime.rb:17:in `call'
  /usr/lib/ruby/vendor_ruby/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/static.rb:84:in `call'
  /usr/lib/ruby/vendor_ruby/rack/sendfile.rb:112:in `call'
  /usr/lib/ruby/vendor_ruby/rails/engine.rb:514:in `call'
  /usr/lib/ruby/vendor_ruby/rails/application.rb:144:in `call'
  /usr/lib/ruby/vendor_ruby/rails/railtie.rb:194:in `public_send'
  /usr/lib/ruby/vendor_ruby/rails/railtie.rb:194:in `method_missing'
  /usr/lib/ruby/vendor_ruby/rack/handler/webrick.rb:60:in `service'
  /usr/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /usr/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /usr/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by Coren** [comment]
I cannot manage to see why it can fail this way. 

Can you try without all your other plugins and tell me if it fails ? the same way ? with the same error message ?
