### ISSUE TITLE
undefined method `permissions'

### ISSUE THREAD

**Issue by ppoektos** [Coren/redmine_advanced_roadmap_v2#26]
```
# rake redmine:plugins:migrate NAME=advanced_roadmap_v2 RAILS_ENV=production
Migrating advanced_roadmap_v2 (Advanced roadmap & milestones plugin)...
==  PresetPermissions: migrating ==============================================
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

undefined method `permissions' for nil:NilClass/var/www/rm260/plugins/advanced_roadmap_v2/db/migrate/003_preset_permissions.rb:4:in `up'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.19/lib/active_record/migration.rb:370:in `up'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.19/lib/active_record/migration.rb:410:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.19/lib/active_record/migration.rb:410:in `block in migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.19/lib/active_record/migration.rb:389:in `migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.19/lib/active_record/migration.rb:528:in `migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.19/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.19/lib/active_record/migration.rb:777:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.19/lib/active_record/migration.rb:777:in `ddl_transaction'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.19/lib/active_record/migration.rb:719:in `block in migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.19/lib/active_record/migration.rb:700:in `each'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.19/lib/active_record/migration.rb:700:in `migrate'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.19/lib/active_record/migration.rb:570:in `up'
/usr/local/rvm/gems/ruby-1.9.3-p327/gems/activerecord-3.2.19/lib/active_record/migration.rb:551:in `migrate'
/var/www/rm260/lib/redmine/plugin.rb:469:in `migrate_plugin'
/var/www/rm260/lib/redmine/plugin.rb:441:in `migrate'
/var/www/rm260/lib/redmine/plugin.rb:452:in `migrate'
/var/www/rm260/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
```

**Comment by slvr9** [comment]
confirm
