### ISSUE TITLE
Redmine inaccessible after installing Advance Roadmap v2

### ISSUE THREAD

**Issue by carukc** [Coren/redmine_advanced_roadmap_v2#30]
Hello,

I'm getting an error when I install this plugin on Redmine v2.6 (running on Ubuntu under phusion, nginx and docker).  Fy first thought was that there might have been a compatibility problem with another plugin so I have removed all but Adv Roadmap but I'm still getting the following error:

ActionView::Template::Error (Missing partial hooks/stylesheet with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :rsb]}. Searched in:
  * "/home/app/htdocs/projects/app/views"
):
    11: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    12: <%= javascript_heads %>
    13: <%= heads_for_theme %>
    14: <%= call_hook :view_layouts_base_html_head %>
    15: 
    16: <%= yield :header_tags -%>
    17: </head>
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/layouts/base.html.erb:14:in `_app_views_layouts_base_html_erb___1777458717933728732_41863980'
  app/controllers/application_controller.rb:465:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:463:in `render_error'
  app/controllers/application_controller.rb:451:in `render_404'
  app/controllers/application_controller.rb:475:in `missing_template'

Do you know what might be causing this problem.

Thanks
Chris

**Comment by carukc** [comment]
my mistake.  I missed step 3:

  Rename the folder to advanced_roadmap_v2

Thanks for the great update to this useful plugin.
