### ISSUE TITLE
Gantt View broken with advanced roadmap v2 enabled

### ISSUE THREAD

**Issue by projectplant** [Coren/redmine_advanced_roadmap_v2#41]
Hi

the gantt view gives a 500 error
```
Processing by GanttsController#show as HTML
  Parameters: {"project_id"=>"test-mbu"}
  Current user: admin (id=1)
  Rendered queries/_filters.html.erb (236.4ms)
  Rendered gantts/show.html.erb within layouts/base (501.5ms)
Completed 500 Internal Server Error in 819ms

ActionView::Template::Error (undefined method `abort?' for #<Redmine::Helpers::Gantt:0x00000005665440>):
    102: 
    103:   # Width of the entire chart
    104:   g_width = ((@gantt.date_to - @gantt.date_from + 1) * zoom).to_i
    105:   @gantt.render(:top => headers_height + 8,
    106:                 :zoom => zoom,
    107:                 :g_width => g_width,
    108:                 :subject_width => subject_width)
  lib/redmine/helpers/gantt.rb:225:in `block (2 levels) in render_project'
  lib/redmine/helpers/gantt.rb:224:in `each'
  lib/redmine/helpers/gantt.rb:224:in `block in render_project'
  lib/redmine/helpers/gantt.rb:276:in `increment_indent'
  lib/redmine/helpers/gantt.rb:217:in `render_project'
  lib/redmine/helpers/gantt.rb:205:in `block in render'
  app/models/project.rb:756:in `block in project_tree'
  app/models/project.rb:752:in `each'
  app/models/project.rb:752:in `project_tree'
  lib/redmine/helpers/gantt.rb:203:in `render'
  app/views/gantts/show.html.erb:105:in `_app_views_gantts_show_html_erb__66866357230285753_36965880'
  app/controllers/gantts_controller.rb:43:in `block (2 levels) in show'
  app/controllers/gantts_controller.rb:42:in `show'
```

Here a screenshot without "advanced roadmap v2":
![auswahl_008](https://cloud.githubusercontent.com/assets/11331755/6524945/9c67666e-c3ff-11e4-9f05-8eddf06305f6.png)

Environment:
  Redmine version                3.0.0.stable.14045
  Ruby version                   2.2.0-p0 (2014-12-25) [x86_64-linux]
  Rails version                  4.2.0
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  advanced_roadmap_v2            2.3.2

**Comment by projectplant** [comment]
fixed, thx!
