### ISSUE TITLE
open redmine web page 500 error directly

### ISSUE THREAD

**Issue by tmc9031** [Coren/redmine_advanced_roadmap_v2#75]
when open redmine web page

```
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.
```

my redmine version as follow

```
Environment:
  Redmine version                3.0.7.stable
  Ruby version                   2.0.0-p648 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               Mysql2
```

**Comment by StylonWang** [comment]
Same internal error here

Environment:
  Redmine version                3.1.4.stable
  Ruby version                   2.1.8-p440 (2015-12-16) [x86_64-linux-gnu]
  Rails version                  4.2.5.2
  Environment                    production
  Database adapter               PostgreSQL

**Comment by dalu** [comment]
```
Started GET "/" for 127.0.0.1 at 2016-06-20 19:13:04 +0200
Processing by WelcomeController#index as HTML
  Current user: admin (id=1)
  Rendered welcome/index.html.erb within layouts/base (11.4ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.2ms)
Completed 500 Internal Server Error in 32ms (ActiveRecord: 1.8ms)

ActionView::Template::Error (Missing partial hooks/_stylesheet with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :rsb]}. Searched in:
  * "/home/redmine/redmine-3.0.4/app/views"
):
    11: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    12: <%= javascript_heads %>
    13: <%= heads_for_theme %>
    14: <%= call_hook :view_layouts_base_html_head %>
    15: <!-- page specific tags -->
    16: <%= yield :header_tags -%>
    17: </head>
  lib/redmine/hook.rb:119:in `block (2 levels) in render_on'
  lib/redmine/hook.rb:117:in `map'
  lib/redmine/hook.rb:117:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:167:in `call_hook'
  app/views/layouts/base.html.erb:14:in `_app_views_layouts_base_html_erb___3772933451381698003_44872060'
  app/controllers/application_controller.rb:469:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:467:in `render_error'
  app/controllers/application_controller.rb:455:in `render_404'
  app/controllers/application_controller.rb:479:in `missing_template'
```

**Comment by Coren** [comment]
Uninstall steps are in the readme: https://github.com/Coren/redmine_advanced_roadmap_v2#uninstall
