### ISSUE TITLE
error: undefined method `around_filter' for CalendarsController:Class

### ISSUE THREAD

**Issue by botsconsultoria** [Coren/redmine_advanced_roadmap_v2#92]
> App 13841 output: Error: The application encountered the following error: undefined method `around_filter' for CalendarsController:Class
App 13841 output: Did you mean?  around_action (NoMethodError)
App 13841 output:     /opt/www/redmine/plugins/advanced_roadmap_v2/lib/advanced_roadmap/calendars_controller_patch.rb:8:in `block in included'
App 13841 output:     /opt/www/redmine/plugins/advanced_roadmap_v2/lib/advanced_roadmap/calendars_controller_patch.rb:6:in `class_eval'
App 13841 output:     /opt/www/redmine/plugins/advanced_roadmap_v2/lib/advanced_roadmap/calendars_controller_patch.rb:6:in `included'
App 13841 output:     /opt/www/redmine/plugins/advanced_roadmap_v2/init.rb:13:in `include'
App 13841 output:     /opt/www/redmine/plugins/advanced_roadmap_v2/init.rb:13:in `<top (required)>'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `block in require'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:291:in `require'
App 13841 output:     /opt/www/redmine/lib/redmine/plugin.rb:175:in `block in load'
App 13841 output:     /opt/www/redmine/lib/redmine/plugin.rb:166:in `each'
App 13841 output:     /opt/www/redmine/lib/redmine/plugin.rb:166:in `load'
App 13841 output:     /opt/www/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `load'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `block in load'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:257:in `load_dependency'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2.1/lib/active_support/dependencies.rb:285:in `load'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/railties-5.2.2.1/lib/rails/engine.rb:657:in `block in load_config_initializer'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:170:in `instrument'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/railties-5.2.2.1/lib/rails/engine.rb:656:in `load_config_initializer'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/railties-5.2.2.1/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/railties-5.2.2.1/lib/rails/engine.rb:613:in `each'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/railties-5.2.2.1/lib/rails/engine.rb:613:in `block in <class:Engine>'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `instance_exec'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/railties-5.2.2.1/lib/rails/initializable.rb:32:in `run'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/railties-5.2.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
App 13841 output:     /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
App 13841 output:     /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
App 13841 output:     /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
App 13841 output:     /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
App 13841 output:     /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/railties-5.2.2.1/lib/rails/initializable.rb:50:in `each'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/railties-5.2.2.1/lib/rails/initializable.rb:50:in `tsort_each_child'
App 13841 output:     /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:415:in `call'
App 13841 output:     /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
App 13841 output:     /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
App 13841 output:     /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each'
App 13841 output:     /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `call'
App 13841 output:     /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
App 13841 output:     /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
App 13841 output:     /usr/local/rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/railties-5.2.2.1/lib/rails/initializable.rb:60:in `run_initializers'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/railties-5.2.2.1/lib/rails/application.rb:361:in `initialize!'
App 13841 output:     /opt/www/redmine/config/environment.rb:14:in `<top (required)>'
App 13841 output:     config.ru:3:in `require'
App 13841 output:     config.ru:3:in `block in <main>'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
App 13841 output:     config.ru:1:in `new'
App 13841 output:     config.ru:1:in `<main>'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/passenger-6.0.2/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/passenger-6.0.2/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/passenger-6.0.2/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/passenger-6.0.2/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:380:in `run_block_and_record_step_progress'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/passenger-6.0.2/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/passenger-6.0.2/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 13841 output:     /usr/local/rvm/gems/ruby-2.6.0/gems/passenger-6.0.2/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2019-04-25 13:13:05.0986 12588/Tz age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /opt/www/redmine: The application encountered the following error: undefined method `around_filter' for CalendarsController:Class
Did you mean?  around_action (NoMethodError)
  Error ID: 86fa410c
  Error details saved to: /tmp/passenger-error-VFGuRb.html

Redmine 4.0.3
Httpd
CentOS 7

**Comment by swatty007** [comment]
having the same issue, are there any news on this? The original plugin is having the same issue.

**Comment by Girmiti2its** [comment]
Facing the same issue, any fix on this ?

**Comment by violettomsk** [comment]
Fixing... I hope.

**Comment by n0rvik** [comment]
I confirm.

```
[~/redmine]$ RAILS_ENV=production bundle exec rake redmine:plugins:migrate
rake aborted!
NoMethodError: undefined method `around_filter' for CalendarsController:Class
Did you mean?  around_action
/mnt/storage/opt/redmine/redmine/plugins/advanced_roadmap_v2/lib/advanced_roadmap/calendars_controller_patch.rb:8:in `block in included'
/mnt/storage/opt/redmine/redmine/plugins/advanced_roadmap_v2/lib/advanced_roadmap/calendars_controller_patch.rb:6:in `class_eval'
/mnt/storage/opt/redmine/redmine/plugins/advanced_roadmap_v2/lib/advanced_roadmap/calendars_controller_patch.rb:6:in `included'
/mnt/storage/opt/redmine/redmine/plugins/advanced_roadmap_v2/init.rb:13:in `include'
/mnt/storage/opt/redmine/redmine/plugins/advanced_roadmap_v2/init.rb:13:in `<top (required)>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
/mnt/storage/opt/redmine/redmine/lib/redmine/plugin.rb:181:in `block in load'
/mnt/storage/opt/redmine/redmine/lib/redmine/plugin.rb:172:in `each'
/mnt/storage/opt/redmine/redmine/lib/redmine/plugin.rb:172:in `load'
/mnt/storage/opt/redmine/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `load'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `block in load'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `load'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:663:in `block in load_config_initializer'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/notifications.rb:170:in `instrument'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:662:in `load_config_initializer'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:619:in `each'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:619:in `block in <class:Engine>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `instance_exec'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `run'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:50:in `each'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:60:in `run_initializers'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/application.rb:361:in `initialize!'
/mnt/storage/opt/redmine/redmine/config/environment.rb:16:in `<top (required)>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/application.rb:337:in `require_environment!'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

```
Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.6.3-p62 (2019-04-16) [x86_64-linux]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.7.14
  Mercurial                      5.2.2
  Bazaar                         2.5.1
  Git                            2.9.3
  Filesystem                     
  Xitolite                       2.9.3
Redmine plugins:
  additionals                    2.0.23
  progressive_projects_list      4.0.0
  redmine_git_hosting            4.0.1
  redmine_issue_badge            0.1.3
  redmine_tags                   4.0.0
  
```

**Comment by Takeuchi-Ikuma** [comment]
With this forked project, I was able to install it without error in Redmine 4.1.0.
Try it.
https://github.com/awk-kazmin/redmine_advanced_roadmap_v2
```
OS:
  Windows 10 Pro 1909 Gen2
  (Bitnami-4.1.0-8)

Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.5.7-p206 (2019-10-01) [x64-mingw32]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp

SCM:
  Git                            2.25.0
  Filesystem                     

Redmine plugins:
  advanced_roadmap_v2            2.4.3
  easy_gantt                     1.12
  redmine_absolute_dates         0.0.4
  redmine_checklists             3.1.16
  redmine_dashboard              2.7.1
  redmine_issue_templates        1.0.0
  redmine_jstoolbar_ext          0.2.1
  redmine_jstoolbar_ext_buttons  0.2.1
  redmine_work_time              0.4.0
  view_customize                 2.5.0
```

**Comment by n0rvik** [comment]
> With this forked project, I was able to install it without error in Redmine 4.1.0.
> Try it.
> https://github.com/awk-kazmin/redmine_advanced_roadmap_v2

Very sorry. No:

> Since original plugin is back on rails, this plugin **won't be maintained anymore.**

**Comment by etaojames** [comment]
master branch can fix the problem below:
NoMethodError: undefined method `around_filter' for CalendarsController:Class
But the roadmap function can not be dispalyed in the system with installing sccessful!
The edition is 4.0.0 or 4.1.1
