### ISSUE TITLE
compatibility with Redmine 5.0x 

### ISSUE THREAD

**Issue by SinghNanak** [Coren/redmine_advanced_roadmap_v2#94]

**Comment by Arean82** [comment]
there is an issue where the calender brakes


I, [2024-11-28T11:58:32.876434 #3362436]  INFO -- : [40049187-e903-420d-bda5-ac54404fea02]   Rendered inline template (Duration: 0.5ms | Allocations: 218)
I, [2024-11-28T11:58:32.913888 #3362436]  INFO -- : [40049187-e903-420d-bda5-ac54404fea02]   Rendered inline template (Duration: 0.4ms | Allocations: 198)
I, [2024-11-28T11:58:33.023036 #3362436]  INFO -- : [40049187-e903-420d-bda5-ac54404fea02]   Rendered layout layouts/base.html.erb (Duration: 491.4ms | Allocations: 176748)
I, [2024-11-28T11:58:33.043353 #3362436]  INFO -- : [40049187-e903-420d-bda5-ac54404fea02] Completed 500 Internal Server Error in 823ms (Views: 380.3ms | ActiveRecord: 228.0ms | Allocations: 274622)
F, [2024-11-28T11:58:33.044256 #3362436] FATAL -- : [40049187-e903-420d-bda5-ac54404fea02]
[40049187-e903-420d-bda5-ac54404fea02] ArgumentError (wrong number of arguments (given 1, expected 3)):
[40049187-e903-420d-bda5-ac54404fea02]
[40049187-e903-420d-bda5-ac54404fea02] plugins/advanced_roadmap/lib/advanced_roadmap/calendars_controller_patch.rb:21:in `new'
[40049187-e903-420d-bda5-ac54404fea02] plugins/advanced_roadmap/lib/advanced_roadmap/calendars_controller_patch.rb:21:in `add_milestones'
